FROM node:24.15.0-alpine

WORKDIR /app
RUN corepack enable

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
RUN pnpm install --frozen-lockfile

COPY . .

EXPOSE 4200
CMD ["pnpm", "start", "--host", "0.0.0.0", "--poll", "1000", "--proxy-config", "proxy.docker.conf.json"]
